---
# tasks file for audit-setup
 - name: Creating a new directory
   file:
      path: "/home/iss/"
      state: directory
 - name: create client file
   copy:
    dest: /home/iss/c1l2i3e4n5t.txt
    content: "{{ cid }}"
 - name: copy cpu monitoring script
   copy:
     src: ./cpumon.sh
     dest: /home/iss/cpumon.sh
     mode: 700
 - name: setup cronjob
   cron:
     minute: "*/2"
     hour: "*"
     day: "*"
     month: "*"
     weekday: "*"
     job: "/home/iss/cpumon.sh > /dev/null 2>&1"
